"""
Public trading bot / open-source algorithmic system catalog.

Fields emphasize what can be verified from public repos/docs.
Performance is UNKNOWN unless a public audited track record exists.
"""

from __future__ import annotations

from src.models.types import empty_performance, pv

BOTS = [
    {
        "id": "bot_freqtrade",
        "name": "Freqtrade",
        "source_url": "https://github.com/freqtrade/freqtrade",
        "language": "Python",
        "market": "Crypto spot & futures (exchange-dependent)",
        "timeframe": "minutes to hours (user-defined)",
        "strategy_id": "strat_freqtrade_roi_stoploss",
        "signals": "Pluggable indicators (TA-Lib/pandas-ta); user strategy classes",
        "entry": "Strategy.populate_entry_trend() conditions",
        "exit": "Exit signals + ROI table + stoploss + trailing stop",
        "position_sizing": "Fixed stake, available balance fractions, or custom callbacks",
        "risk_management": "Stoploss, max open trades, protection plugins (cooldown, etc.)",
        "execution": "CCXT exchange API; dry-run and live modes",
        "data": "OHLCV from exchanges; optional informative pairs",
        "backtest_notes": "Built-in backtester; results highly strategy-specific; easy to overfit hyperopt",
        "performance": empty_performance(),
        "limitations": "No universal edge; hyperopt overfitting risk; exchange fees/slippage often underestimated",
        "code_inspected": True,
        "inspection_summary": (
            "Core loop loads OHLCV, computes indicators in user strategy, generates entries/exits, "
            "applies ROI/stoploss, sizes stakes, and routes orders via CCXT. Hyperopt optimizes parameters "
            "against backtest metrics — a major overfitting vector if abused."
        ),
    },
    {
        "id": "bot_hummingbot",
        "name": "Hummingbot",
        "source_url": "https://github.com/hummingbot/hummingbot",
        "language": "Python",
        "market": "Crypto CEX/DEX",
        "timeframe": "seconds to minutes",
        "strategy_id": "strat_hummingbot_avellaneda",
        "signals": "Fair value mid; inventory skew; optional Avellaneda-Stoikov reservation price",
        "entry": "Post bid/ask around reservation price / spreads",
        "exit": "Inventory-targeted quote adjustments; optional hanging order logic",
        "position_sizing": "Order amount configs; inventory targets",
        "risk_management": "Inventory band, kill switches, exchange circuit patterns",
        "execution": "Connector architecture to CEX/DEX; websocket order books",
        "data": "Live order books, trades, balances",
        "backtest_notes": "Strategy backtesting support exists but MM backtests are microstructure-sensitive",
        "performance": empty_performance(),
        "limitations": "Adverse selection vs professionals; latency; toxic flow on some venues",
        "code_inspected": True,
        "inspection_summary": (
            "Strategy modules compute reservation prices and optimal spreads (Avellaneda-Stoikov variant), "
            "maintain inventory targets, and manage two-sided quotes through exchange connectors."
        ),
    },
    {
        "id": "bot_jesse",
        "name": "Jesse",
        "source_url": "https://github.com/jesse-ai/jesse",
        "language": "Python",
        "market": "Crypto",
        "timeframe": "user-defined candles",
        "strategy_id": None,
        "signals": "User-coded indicators/events",
        "entry": "Strategy event hooks",
        "exit": "Strategy exits + stops",
        "position_sizing": "Configurable routes / sizing helpers",
        "risk_management": "Stops; exchange constraints",
        "execution": "Exchange integrations",
        "data": "Candle data import",
        "backtest_notes": "Research-oriented backtester with metrics reporting",
        "performance": empty_performance(),
        "limitations": "Edge depends entirely on user strategy quality",
        "code_inspected": False,
        "inspection_summary": "UNKNOWN — framework inspected at documentation level only in this release",
    },
    {
        "id": "bot_octobot",
        "name": "OctoBot",
        "source_url": "https://github.com/Drakkar-Software/OctoBot",
        "language": "Python",
        "market": "Crypto",
        "timeframe": "varies",
        "strategy_id": None,
        "signals": "Evaluator / tentacle plugin system",
        "entry": "Evaluator decisions",
        "exit": "Evaluator decisions",
        "position_sizing": "Risk plugins",
        "risk_management": "Configurable risk modules",
        "execution": "Exchange tentacles",
        "data": "Market + social evaluators optional",
        "backtest_notes": "Supports backtesting via tentacles",
        "performance": empty_performance(),
        "limitations": "Complex plugin surface; strategy quality varies",
        "code_inspected": False,
        "inspection_summary": "UNKNOWN",
    },
    {
        "id": "bot_gekko",
        "name": "Gekko (archived lineage)",
        "source_url": "https://github.com/askmike/gekko",
        "language": "JavaScript",
        "market": "Crypto",
        "timeframe": "candles",
        "strategy_id": None,
        "signals": "Plugin strategies (MACD, RSI, etc.)",
        "entry": "Indicator cross logic typical",
        "exit": "Indicator exits",
        "position_sizing": "Simple portfolio allocation",
        "risk_management": "Limited vs modern frameworks",
        "execution": "Exchange wrappers",
        "data": "Candle importer",
        "backtest_notes": "Popular historically; many public strategies are overfit toy examples",
        "performance": empty_performance(),
        "limitations": "Archived; educational more than production edge",
        "code_inspected": False,
        "inspection_summary": "Historical reference system; treat public strategy posts as weak evidence",
    },
    {
        "id": "bot_zenbot",
        "name": "Zenbot",
        "source_url": "https://github.com/DeviaVir/zenbot",
        "language": "JavaScript",
        "market": "Crypto",
        "timeframe": "minutes",
        "strategy_id": None,
        "signals": "Built-in strategies (trend following, mean reversion variants)",
        "entry": "Strategy-dependent",
        "exit": "Strategy-dependent",
        "position_sizing": "Configurable",
        "risk_management": "Basic stops",
        "execution": "Exchange APIs",
        "data": "Trade history / candles",
        "backtest_notes": "Simulated trades; not a verified live edge",
        "performance": empty_performance(),
        "limitations": "Maintenance uneven; no verified alpha claim",
        "code_inspected": False,
        "inspection_summary": "UNKNOWN",
    },
    {
        "id": "bot_nautilus",
        "name": "NautilusTrader",
        "source_url": "https://github.com/nautechsystems/nautilus_trader",
        "language": "Python/Rust",
        "market": "Multi-asset (adapters)",
        "timeframe": "event-driven / high resolution capable",
        "strategy_id": None,
        "signals": "User strategy actors",
        "entry": "User-defined",
        "exit": "User-defined",
        "position_sizing": "User-defined",
        "risk_management": "Risk engine components",
        "execution": "Professional event-driven execution model",
        "data": "Catalog of bars/ticks/order books",
        "backtest_notes": "High-fidelity backtesting focus — better microstructure realism than toy bots",
        "performance": empty_performance(),
        "limitations": "Framework, not a strategy; edge still user-supplied",
        "code_inspected": True,
        "inspection_summary": (
            "Event-driven engine with cache, data, execution, and risk components; designed for "
            "research-to-live parity rather than shipping a single profitable strategy."
        ),
    },
    {
        "id": "bot_hftbacktest",
        "name": "hftbacktest",
        "source_url": "https://github.com/nkaz001/hftbacktest",
        "language": "Python",
        "market": "Equities/crypto microstructure research",
        "timeframe": "hft / event",
        "strategy_id": "strat_order_flow_toxicity",
        "signals": "Queue position / order book features (user-built)",
        "entry": "User market-making or taking logic",
        "exit": "User logic",
        "position_sizing": "User logic",
        "risk_management": "User logic",
        "execution": "Simulated queue-aware fills",
        "data": "Full order book / trade feeds for backtest",
        "backtest_notes": "Research tool for HFT MM; does not provide a production edge by itself",
        "performance": empty_performance(),
        "limitations": "Requires expensive data; strategy still proprietary to researcher",
        "code_inspected": True,
        "inspection_summary": (
            "Provides queue-based market replay and inventory-aware MM examples; useful for testing "
            "latency/queue assumptions, not a turnkey alpha product."
        ),
    },
    {
        "id": "bot_finrl",
        "name": "FinRL",
        "source_url": "https://github.com/AI4Finance-Foundation/FinRL",
        "language": "Python",
        "market": "Equities (examples), extensible",
        "timeframe": "days (typical examples)",
        "strategy_id": "strat_finrl_portfolio",
        "signals": "Learned RL policy over market state features",
        "entry": "Policy action → weights / trades",
        "exit": "Policy reallocation",
        "position_sizing": "Portfolio weight actions",
        "risk_management": "Environment-level constraints in examples; often insufficient vs real trading",
        "execution": "Usually abstracted fills in research envs",
        "data": "Yahoo/other daily price examples common",
        "backtest_notes": "Research benchmarks; published metrics often ignore realistic costs/slippage regimes",
        "performance": empty_performance(),
        "limitations": "Overfitting, non-stationarity, unrealistic execution — place in weak-evidence watchlist unless carefully validated",
        "code_inspected": True,
        "inspection_summary": (
            "Builds OpenAI-Gym-style market environments and trains DRL agents (A2C/PPO/etc.). "
            "Example pipelines emphasize research reproducibility more than live microstructure realism."
        ),
    },
    {
        "id": "bot_qlib",
        "name": "Microsoft Qlib",
        "source_url": "https://github.com/microsoft/qlib",
        "language": "Python",
        "market": "Equities (China/US examples)",
        "timeframe": "days",
        "strategy_id": "strat_two_sigma_ml_equity",
        "signals": "ML models (LightGBM, Transformer variants, etc.) on alpha factors",
        "entry": "Top-k / drop-out portfolio from prediction scores",
        "exit": "Rebalance by score decay",
        "position_sizing": "Rank-based portfolio constructors",
        "risk_management": "Limiters / cost models available in workflow",
        "execution": "Research backtest executor",
        "data": "Qlib data bundles; provider-dependent",
        "backtest_notes": "Strong research workflow; published example metrics are not live fund returns",
        "performance": empty_performance(),
        "limitations": "Alpha decay; data snooping if feature libraries searched aggressively",
        "code_inspected": True,
        "inspection_summary": (
            "End-to-end quant research platform: data layer, operators, models, portfolio generation, "
            "and backtest. Useful reference for industrial ML quant workflows."
        ),
    },
    {
        "id": "bot_vectorbt",
        "name": "VectorBT",
        "source_url": "https://github.com/polakowo/vectorbt",
        "language": "Python",
        "market": "Any OHLCV research",
        "timeframe": "user-defined",
        "strategy_id": None,
        "signals": "User vectorized signals",
        "entry": "Signal arrays",
        "exit": "Signal arrays",
        "position_sizing": "Vectorized sizing functions",
        "risk_management": "User-defined",
        "execution": "Research simulation",
        "data": "NumPy/Pandas/Polars workflows",
        "backtest_notes": "Extremely fast research; can accelerate overfitting if abused",
        "performance": empty_performance(),
        "limitations": "Not a bot — research library",
        "code_inspected": False,
        "inspection_summary": "Library-level review only",
    },
    {
        "id": "bot_backtrader",
        "name": "Backtrader",
        "source_url": "https://github.com/mementum/backtrader",
        "language": "Python",
        "market": "Any",
        "timeframe": "user-defined",
        "strategy_id": None,
        "signals": "User indicators",
        "entry": "Strategy.next() orders",
        "exit": "Strategy orders / stops",
        "position_sizing": "Sizers",
        "risk_management": "Brackets/stops",
        "execution": "Brokers simulated; some live integrations community-maintained",
        "data": "CSV/feeds",
        "backtest_notes": "Classic retail research framework",
        "performance": empty_performance(),
        "limitations": "Strategy-dependent; many public examples ignore costs",
        "code_inspected": False,
        "inspection_summary": "Framework reference",
    },
    {
        "id": "bot_zipline",
        "name": "Zipline / Zipline-Reloaded",
        "source_url": "https://github.com/stefan-jansen/zipline-reloaded",
        "language": "Python",
        "market": "Equities (typical)",
        "timeframe": "days",
        "strategy_id": "strat_cross_sectional_momentum",
        "signals": "Pipeline factors",
        "entry": "Pipeline output → order_target_percent",
        "exit": "Rebalance",
        "position_sizing": "Target weights",
        "risk_management": "User constraints",
        "execution": "Simulated slippage models",
        "data": "Bundle ingestion",
        "backtest_notes": "Quantopian lineage; educational factor workflows",
        "performance": empty_performance(),
        "limitations": "Data licensing; research ≠ live capacity",
        "code_inspected": True,
        "inspection_summary": (
            "Pipeline API computes point-in-time factors; algorithm API rebalances to target weights "
            "with commission/slippage models — good for factor research hygiene."
        ),
    },
    {
        "id": "bot_lean_quantconnect",
        "name": "QuantConnect Lean",
        "source_url": "https://github.com/QuantConnect/Lean",
        "language": "C# / Python",
        "market": "Multi-asset",
        "timeframe": "ticks to days",
        "strategy_id": None,
        "signals": "User algorithms",
        "entry": "QCAlgorithm order APIs",
        "exit": "User logic",
        "position_sizing": "User logic / portfolio construction modules",
        "risk_management": "Risk modules available",
        "execution": "Brokerage models; live deployments on QC cloud",
        "data": "QC data lake / custom",
        "backtest_notes": "Professional-grade research engine used by many public shared algorithms",
        "performance": empty_performance(),
        "limitations": "Public shared algos vary wildly in quality; treat as unverified",
        "code_inspected": True,
        "inspection_summary": (
            "Event-driven algorithm framework with data feeds, scheduling, portfolio, and brokerage "
            "abstractions; hosts many community strategies of uneven evidence quality."
        ),
    },
    {
        "id": "bot_elegentrl",
        "name": "ElegantRL",
        "source_url": "https://github.com/AI4Finance-Foundation/ElegantRL",
        "language": "Python",
        "market": "Research finance envs",
        "timeframe": "env-dependent",
        "strategy_id": "strat_rl_execution",
        "signals": "DRL policies",
        "entry": "Policy actions",
        "exit": "Policy actions",
        "position_sizing": "Action space dependent",
        "risk_management": "Env constraints",
        "execution": "Simulated",
        "data": "Env-provided",
        "backtest_notes": "Research library",
        "performance": empty_performance(),
        "limitations": "Not a proven trading edge",
        "code_inspected": False,
        "inspection_summary": "Companion RL library to FinRL ecosystem",
    },
    {
        "id": "bot_tensortrade",
        "name": "TensorTrade",
        "source_url": "https://github.com/tensortrade-org/tensortrade",
        "language": "Python",
        "market": "Research",
        "timeframe": "env-dependent",
        "strategy_id": "strat_finrl_portfolio",
        "signals": "RL feature pipelines",
        "entry": "Actions",
        "exit": "Actions",
        "position_sizing": "Actions",
        "risk_management": "Reward shaping",
        "execution": "Simulated exchange components",
        "data": "Stream/feature modules",
        "backtest_notes": "Composable RL trading components",
        "performance": empty_performance(),
        "limitations": "Research toy risk; weak live evidence",
        "code_inspected": False,
        "inspection_summary": "UNKNOWN",
    },
    {
        "id": "bot_pybroker",
        "name": "PyBroker",
        "source_url": "https://github.com/edtechre/pybroker",
        "language": "Python",
        "market": "Equities/crypto research",
        "timeframe": "user-defined",
        "strategy_id": None,
        "signals": "ML model integration helpers",
        "entry": "User model predictions",
        "exit": "User rules",
        "position_sizing": "Helpers",
        "risk_management": "User",
        "execution": "Backtest focus",
        "data": "DataSource abstractions",
        "backtest_notes": "ML-friendly backtesting",
        "performance": empty_performance(),
        "limitations": "No inherent edge",
        "code_inspected": False,
        "inspection_summary": "UNKNOWN",
    },
    {
        "id": "bot_backtesting_py",
        "name": "Backtesting.py",
        "source_url": "https://github.com/kernc/backtesting.py",
        "language": "Python",
        "market": "OHLCV research",
        "timeframe": "user-defined",
        "strategy_id": None,
        "signals": "User Strategy class indicators",
        "entry": "buy/sell helpers",
        "exit": "close / reverse",
        "position_sizing": "fractional / size params",
        "risk_management": "SL/TP parameters",
        "execution": "Simple bar simulation",
        "data": "Pandas OHLCV",
        "backtest_notes": "Convenient for teaching; easy to overfit",
        "performance": empty_performance(),
        "limitations": "Bar-based realism limits",
        "code_inspected": False,
        "inspection_summary": "Library reference",
    },
    {
        "id": "bot_ccxt",
        "name": "CCXT (execution library, not strategy)",
        "source_url": "https://github.com/ccxt/ccxt",
        "language": "Python/JS/PHP",
        "market": "Crypto exchanges",
        "timeframe": "n/a",
        "strategy_id": None,
        "signals": "n/a",
        "entry": "n/a",
        "exit": "n/a",
        "position_sizing": "n/a",
        "risk_management": "n/a",
        "execution": "Unified exchange API",
        "data": "Tickers, OHLCV, order books",
        "backtest_notes": "Not a backtester",
        "performance": empty_performance(),
        "limitations": "Infrastructure component only",
        "code_inspected": False,
        "inspection_summary": "Widely used execution/data dependency for crypto bots",
    },
    {
        "id": "bot_quantlib",
        "name": "QuantLib",
        "source_url": "https://github.com/lballabio/QuantLib",
        "language": "C++",
        "market": "Derivatives pricing",
        "timeframe": "n/a",
        "strategy_id": "strat_convertible_arb",
        "signals": "Pricing models (not trade signals)",
        "entry": "n/a",
        "exit": "n/a",
        "position_sizing": "n/a",
        "risk_management": "Risk Greeks computation support",
        "execution": "n/a",
        "data": "Market quotes for calibration",
        "backtest_notes": "Pricing library used inside RV/vol strategies",
        "performance": empty_performance(),
        "limitations": "Not a trading bot",
        "code_inspected": False,
        "inspection_summary": "Industry-standard pricing building block",
    },
]


def extra_bot_stubs():
    """Additional publicly documented systems for breadth."""
    stubs = [
        ("bot_superalgos", "Superalgos", "https://github.com/Superalgos/Superalgos", "JavaScript", "Crypto"),
        ("bot_basana", "Basana", "https://github.com/gbeced/basana", "Python", "Crypto"),
        ("bot_passivbot", "Passivbot", "https://github.com/enarjord/passivbot", "Python", "Crypto"),
        ("bot_octane", "Octane / community forks", None, "UNKNOWN", "Crypto"),
        ("bot_tribeca", "Tribeca (historical MM bot)", "https://github.com/michaelgrosner/tribeca", "TypeScript", "Crypto"),
        ("bot_catalyst_enzian", "Catalyst (historical)", None, "Python", "Crypto"),
        ("bot_pysystemtrade", "pysystemtrade (Rob Carver)", "https://github.com/robcarver17/pysystemtrade", "Python", "Futures"),
        ("bot_pysystemtrade_examples", "pysystemtrade examples", "https://github.com/robcarver17/pysystemtrade", "Python", "Futures"),
        ("bot_tradingview_pinescript_ecosystem", "TradingView Pine Script Public Strategies", "https://www.tradingview.com", "Pine Script", "Multi"),
        ("bot_tv_lux_algo_style_public", "Public TV indicator strategies (generic)", "https://www.tradingview.com", "Pine Script", "Multi"),
        ("bot_moondev", "MoonDev style educational bots (public streams)", None, "Python", "Crypto"),
        ("bot_cryptofeed", "Cryptofeed", "https://github.com/bmoscon/cryptofeed", "Python", "Crypto data"),
        ("bot_tardis_machine_examples", "Tardis.dev example bots", "https://docs.tardis.dev", "UNKNOWN", "Crypto HFT research"),
        ("bot_arctic_data", "Arctic / market data research stacks", None, "Python", "Multi"),
        ("bot_vnpy", "VeighNa (vn.py)", "https://github.com/vnpy/vnpy", "Python", "China markets/crypto"),
        ("bot_rqalpha", "RQAlpha", "https://github.com/ricequant/rqalpha", "Python", "China equities"),
        ("bot_ulego", "Uqer/Ricequant research lineage tools", None, "Python", "China equities"),
        ("bot_joinquant_edu", "JoinQuant educational platform strategies", None, "Python", "China equities"),
        ("bot_ptrade", "PTrade research", None, "Python", "China equities"),
        ("bot_backtrader_china_forks", "Backtrader China forks", None, "Python", "China equities"),
        ("bot_lean_options", "Lean Options Algorithms (community)", "https://github.com/QuantConnect/Lean", "C#/Python", "Options"),
        ("bot_optionlab", "OptionLab", None, "Python", "Options research"),
        ("bot_vollib", "Vollib", None, "Python", "Options pricing"),
        ("bot_mibian", "Mibian options", None, "Python", "Options pricing"),
        ("bot_pyfolio", "PyFolio", "https://github.com/quantopian/pyfolio", "Python", "Analytics"),
        ("bot_empyrical", "Empyrical", "https://github.com/quantopian/empyrical", "Python", "Analytics"),
        ("bot_alphalens", "Alphalens", "https://github.com/quantopian/alphalens", "Python", "Factor research"),
        ("bot_bt_library", "bt – flexible backtesting", "https://github.com/pmorissette/bt", "Python", "Multi"),
        ("bot_ffn", "ffn", "https://github.com/pmorissette/ffn", "Python", "Analytics"),
        ("bot_riskfolio", "Riskfolio-Lib", "https://github.com/dcajasn/Riskfolio-Lib", "Python", "Portfolio"),
        ("bot_skfolio", "skfolio", None, "Python", "Portfolio"),
        ("bot_cvxportfolio", "cvxportfolio", "https://github.com/cvxgrp/cvxportfolio", "Python", "Portfolio"),
        ("bot_epymetheus", "Epyetheus", None, "Python", "Portfolio"),
        ("bot_mlfinlab_lineage", "MlFinLab lineage / Hudson & Thames materials", None, "Python", "Equities research"),
        ("bot_afml_code", "Advances in Financial ML code companions", None, "Python", "Equities research"),
        ("bot_ta_lib", "TA-Lib", None, "C/Python", "Indicators"),
        ("bot_pandas_ta", "Pandas-TA", "https://github.com/twopirllc/pandas-ta", "Python", "Indicators"),
        ("bot_tulipindicators", "Tulip Indicators", None, "C", "Indicators"),
        ("bot_finta", "FinTA", None, "Python", "Indicators"),
        ("bot_stockstats", "Stockstats", None, "Python", "Indicators"),
        ("bot_yfinance_research", "yfinance-powered retail strategies", "https://github.com/ranaroussi/yfinance", "Python", "Equities"),
        ("bot_polygon_examples", "Polygon.io example algos", None, "Python", "Equities"),
        ("bot_alpaca_examples", "Alpaca example algos", "https://github.com/alpacahq", "Python", "Equities"),
        ("bot_ib_insync", "ib_insync trading scripts", "https://github.com/erdewit/ib_insync", "Python", "Multi"),
        ("bot_brilliant_crossing_public", "Public brilliant-crossing style MM experiments", None, "UNKNOWN", "Crypto"),
        ("bot_grid_bots_generic", "Exchange native grid bots (Binance/etc.)", None, "UNKNOWN", "Crypto"),
        ("bot_twap_vwap_algos", "Broker VWAP/TWAP algorithm templates", None, "UNKNOWN", "Equities"),
        ("bot_arrival_price_algo", "Arrival-price execution algo research code", None, "UNKNOWN", "Equities"),
        ("bot_implementation_shortfall", "Implementation shortfall algo research", None, "UNKNOWN", "Equities"),
        ("bot_avellaneda_stoikov_notebooks", "Public Avellaneda-Stoikov notebooks", None, "Python", "MM research"),
        ("bot_glft_mm_notebooks", "Guéant-Lehalle-Fernandez-Tapia MM notebooks", None, "Python", "MM research"),
        ("bot_orderbook_rl", "Order book RL research repos (various)", None, "Python", "HFT research"),
        ("bot_lob_forecasting", "LOB forecasting academic code releases", None, "Python", "HFT research"),
        ("bot_deep_lob", "DeepLOB public implementations", None, "Python", "HFT research"),
        ("bot_spread_trading_ib", "IB spread trading example bots", None, "Python", "Futures/Options"),
        ("bot_calendar_spread_auto", "Calendar spread automation examples", None, "Python", "Futures"),
        ("bot_stat_arb_course_code", "Public university stat-arb course code", None, "Python", "Equities"),
        ("bot_pairs_trading_notebooks", "Gatev pairs replication notebooks", None, "Python", "Equities"),
        ("bot_tsmom_replication", "TSMOM replication notebooks", None, "Python", "Futures"),
        ("bot_momentum_crash_study", "Momentum crash study code", None, "Python", "Equities"),
        ("bot_carry_replication", "FX carry replication notebooks", None, "Python", "FX"),
        ("bot_risk_parity_notebooks", "Risk parity construction notebooks", None, "Python", "Multi"),
        ("bot_hrp_lopez_de_prado", "Hierarchical Risk Parity implementations", None, "Python", "Portfolio"),
        ("bot_meta_labeling", "Meta-labeling example code (AFML)", None, "Python", "Equities"),
        ("bot_fracdiff", "Fractional differentiation feature code", None, "Python", "Research"),
        ("bot_cpd_bocpd", "Bayesian online change-point detection research code", None, "Python", "Regime research"),
        ("bot_hmm_regime", "HMM regime-switching trading notebooks", None, "Python", "Regime research"),
        ("bot_garch_vol_target", "GARCH vol-targeting strategy notebooks", None, "Python", "Multi"),
        ("bot_har_rv", "HAR-RV forecasting notebooks", None, "Python", "Volatility"),
        ("bot_vix_basis", "VIX basis research notebooks", None, "Python", "Volatility"),
        ("bot_vrp_harvest", "VRP harvest educational notebooks", None, "Python", "Volatility"),
        ("bot_dispersion_notebooks", "Dispersion trading notebooks", None, "Python", "Options"),
        ("bot_earnings_drift_code", "PEAD replication code", None, "Python", "Equities"),
        ("bot_fundamentals_point_in_time", "Point-in-time fundamentals pipelines", None, "Python", "Equities"),
        ("bot_satellite_alt_data_demo", "Public satellite alt-data demo pipelines", None, "Python", "Equities"),
        ("bot_sentiment_stocktwits", "StockTwits/Twitter sentiment toy bots", None, "Python", "Equities"),
        ("bot_reddit_wsb_sentiment", "Reddit WSB sentiment research code", None, "Python", "Equities"),
        ("bot_newsapi_trading", "NewsAPI-driven trading toys", None, "Python", "Equities"),
        ("bot_edgar_nlp", "SEC EDGAR NLP trading research", None, "Python", "Equities"),
        ("bot_10k_embedding_alpha", "10-K embedding alpha research repos", None, "Python", "Equities"),
        ("bot_crypto_funding_harvester", "Public funding-rate harvester bots", None, "Python", "Crypto"),
        ("bot_crypto_basis_bot", "Public cash-and-carry crypto bots", None, "Python", "Crypto"),
        ("bot_triangular_arb_bot", "Public triangular arb bots", None, "Python", "Crypto"),
        ("bot_cross_exchange_arb", "Public cross-exchange arb bots", None, "Python", "Crypto"),
        ("bot_mev_searcher_edu", "MEV searcher educational repos", None, "Solidity/Python", "Crypto"),
        ("bot_uniswap_mm", "Uniswap LP / MM strategies public", None, "Solidity/Python", "Crypto DEX"),
        ("bot_arrakis_style_lp", "Public concentrated LP managers research", None, "Solidity", "Crypto DEX"),
        ("bot_gamma_strategies_lp", "Public active LP strategy research", None, "UNKNOWN", "Crypto DEX"),
    ]
    return stubs
