"""
Publicly documented strategy catalog.

Evidence discipline:
- Descriptions reflect PUBLIC characterizations only
- Proprietary internals are labeled UNKNOWN / SPECULATIVE
- Academic / open strategies can be more concrete when source code or papers exist
"""

from __future__ import annotations

from src.models.types import empty_performance, pv, ptext


def _perf(**kwargs):
    p = empty_performance()
    for k, v in kwargs.items():
        if k in p:
            p[k] = v
    return p


# Core strategies with richer public documentation
STRATEGIES = [
    {
        "id": "strat_medallion_style_stat_arb",
        "name": "Medallion-Style Short-Horizon Statistical Prediction (Public Characterization)",
        "organization_ids": ["org_renaissance_technologies", "org_renaissance_medallion"],
        "categories": ["Statistical arbitrage", "Machine learning", "Mean reversion", "High frequency"],
        "market": "Primarily liquid US and international equities/futures (exact book UNKNOWN)",
        "asset_class": "Multi-asset (publicly characterized as diversified short-horizon)",
        "timeframe": "minutes",
        "core_edge": "STATISTICAL",
        "signal": ptext(
            "Public sources describe ensembles of short-horizon predictive signals from price/volume and other features; exact features UNKNOWN.",
            "STRONGLY_SUPPORTED",
        ),
        "entry": ptext(
            "Model-predicted positive expected return after costs; thresholds UNKNOWN.",
            "INFERRED",
        ),
        "exit": ptext(
            "Short holding periods; continuous re-forecasting; exact exit rules UNKNOWN.",
            "INFERRED",
        ),
        "position_sizing": ptext(
            "Highly constrained optimization with risk limits; Kelly-like speculation is SPECULATIVE.",
            "SPECULATIVE",
        ),
        "risk_management": ptext(
            "Strict risk overlays and diversification across many weak signals (public interviews/books).",
            "STRONGLY_SUPPORTED",
        ),
        "hedging": ptext("Market-neutral / hedged characterization common in public literature.", "STRONGLY_SUPPORTED"),
        "execution": ptext("Low-latency execution important; proprietary stack UNKNOWN.", "INFERRED"),
        "automation": ptext("Fully systematic / automated per public accounts.", "CONFIRMED"),
        "data_requirements": ptext("High-quality historical market data; alternative data role UNKNOWN.", "INFERRED"),
        "performance": _perf(
            annualized_return=pv(None, "UNKNOWN", "Net returns widely reported in secondary sources but not confirmed here from primary filings"),
            sharpe=pv(None, "UNKNOWN", "Extraordinary Sharpe claims circulate; treat as unverified unless primary source attached"),
            years_operating=pv(35, "ESTIMATED", "Medallion operating since late 1980s"),
            max_drawdown=pv(None, "UNKNOWN"),
            consistency_note=pv("Public books/articles claim multi-decade persistence", "ESTIMATED"),
        ),
        "edge_score": 92,
        "quality_score": 88,
        "reproducibility_score": 8,
        "implementation_difficulty": 10,
        "regime_dependency_score": 40,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_zuckerman_man_who_solved_market", "src_renaissance_wikipedia_summary"],
        "research_interest": 98,
    },
    {
        "id": "strat_cross_sectional_momentum",
        "name": "Cross-Sectional Equity Momentum",
        "organization_ids": ["org_aqr_capital_management", "org_aqr_momentum_factor_desk", "org_man_group"],
        "categories": ["Momentum", "Cross-sectional momentum", "Low frequency"],
        "market": "Global equities",
        "asset_class": "Equity",
        "timeframe": "months",
        "core_edge": "BEHAVIORAL",
        "signal": ptext(
            "Rank assets by past 3–12 month returns excluding recent month; long winners / short losers.",
            "CONFIRMED",
        ),
        "entry": ptext("Rebalance on schedule into top/bottom momentum quantiles.", "CONFIRMED"),
        "exit": ptext("Exit when rank falls out of selected quantile at next rebalance.", "CONFIRMED"),
        "position_sizing": ptext("Equal-weight or risk-parity within sleeves; volatility scaling common.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Sector/country neutralization; volatility targeting; drawdown controls.", "STRONGLY_SUPPORTED"),
        "hedging": ptext("Often run long-short market-neutral or long-only factor tilts.", "CONFIRMED"),
        "execution": ptext("Periodic rebalance with transaction-cost optimization.", "STRONGLY_SUPPORTED"),
        "automation": ptext("Fully systematizable; widely automated in industry.", "CONFIRMED"),
        "data_requirements": ptext("Total return price histories, corporate actions, investability filters.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(0.4, "ESTIMATED", "Long-run factor Sharpe often cited ~0.3–0.6 before costs; varies by sample"),
            annualized_return=pv(None, "UNKNOWN"),
            max_drawdown=pv(None, "UNKNOWN", "Momentum crashes documented e.g. 2009"),
            years_operating=pv(30, "ESTIMATED", "Academic factor since Jegadeesh/Titman 1993; industry longer"),
            crisis_performance=pv("Poor in sharp momentum crash regimes", "ESTIMATED", "Documented in momentum crash literature"),
        ),
        "edge_score": 72,
        "quality_score": 80,
        "reproducibility_score": 85,
        "implementation_difficulty": 4,
        "regime_dependency_score": 70,
        "evidence_level": "CONFIRMED",
        "public_sources": ["src_jegadeesh_titman_1993", "src_aqr_momentum_paper"],
        "research_interest": 90,
    },
    {
        "id": "strat_time_series_trend_following",
        "name": "Time-Series Trend Following (CTA)",
        "organization_ids": [
            "org_winton_group",
            "org_man_ahl",
            "org_aspect_capital",
            "org_transtrend",
            "org_campbell_company",
        ],
        "categories": ["Trend following", "Momentum", "Macro", "Low frequency"],
        "market": "Futures across equities, rates, FX, commodities",
        "asset_class": "Multi-asset futures",
        "timeframe": "weeks",
        "core_edge": "BEHAVIORAL",
        "signal": ptext(
            "Price above/below moving averages or positive time-series momentum; multi-horizon blends common.",
            "CONFIRMED",
        ),
        "entry": ptext("Enter long/short when trend signal exceeds threshold.", "CONFIRMED"),
        "exit": ptext("Exit or reverse on signal flip; trailing stops sometimes used.", "STRONGLY_SUPPORTED"),
        "position_sizing": ptext("Volatility targeting / risk parity across markets is standard public practice.", "CONFIRMED"),
        "risk_management": ptext("Vol scaling, correlation-aware allocation, max leverage caps.", "CONFIRMED"),
        "hedging": ptext("Diversification across uncorrelated futures; not classic beta hedge.", "STRONGLY_SUPPORTED"),
        "execution": ptext("Mostly daily/weekly; some intraday overlays.", "STRONGLY_SUPPORTED"),
        "automation": ptext("Highly automated systematic CTAs.", "CONFIRMED"),
        "data_requirements": ptext("Futures prices, rolls, volatility estimates.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(0.5, "ESTIMATED", "Long-run CTA trend Sharpe often cited ~0.4–0.7; path dependent"),
            years_operating=pv(40, "ESTIMATED"),
            crisis_performance=pv("Historically often positive in equity crises (crisis alpha narrative)", "ESTIMATED", "Supported by CTA research literature"),
            max_drawdown=pv(None, "UNKNOWN"),
        ),
        "edge_score": 78,
        "quality_score": 82,
        "reproducibility_score": 88,
        "implementation_difficulty": 3,
        "regime_dependency_score": 65,
        "evidence_level": "CONFIRMED",
        "public_sources": ["src_moskowitz_tsmom", "src_hurst_trend_following"],
        "research_interest": 93,
    },
    {
        "id": "strat_market_making_equity",
        "name": "Electronic Equity Market Making",
        "organization_ids": [
            "org_virtu_financial",
            "org_citadel_securities",
            "org_jane_street",
            "org_xtx_markets",
            "org_hudson_river_trading",
        ],
        "categories": ["Market making", "Liquidity provision", "High frequency", "Order-flow trading"],
        "market": "Equities / ETFs",
        "asset_class": "Equity",
        "timeframe": "hft",
        "core_edge": "EXECUTION",
        "signal": ptext(
            "Microprice, queue position, inventory, short-term order-flow imbalance; exact models proprietary.",
            "INFERRED",
        ),
        "entry": ptext("Post bid/ask; selectively take when edge vs adverse selection.", "STRONGLY_SUPPORTED"),
        "exit": ptext("Inventory mean-reversion; skew quotes; hard flatten limits.", "STRONGLY_SUPPORTED"),
        "position_sizing": ptext("Inventory caps; risk units by symbol volatility and ADV.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Kill switches, fat-finger limits, venue risk, toxicity filters.", "CONFIRMED"),
        "hedging": ptext("ETF/index/correlated hedges for residual inventory.", "STRONGLY_SUPPORTED"),
        "execution": ptext("Co-located matching-engine access; smart order routing.", "CONFIRMED"),
        "automation": ptext("Near-fully automated.", "CONFIRMED"),
        "data_requirements": ptext("Full depth/L3, proprietary normalized market data.", "CONFIRMED"),
        "performance": _perf(
            years_operating=pv(15, "ESTIMATED"),
            sharpe=pv(None, "UNKNOWN"),
            annualized_return=pv(None, "UNKNOWN", "Public firms disclose trading income not strategy Sharpe"),
        ),
        "edge_score": 85,
        "quality_score": 75,
        "reproducibility_score": 12,
        "implementation_difficulty": 10,
        "regime_dependency_score": 55,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_virtu_10k", "src_hft_academic_survey"],
        "research_interest": 86,
    },
    {
        "id": "strat_stat_arb_pairs",
        "name": "Pairs / Residual Mean-Reversion Stat Arb",
        "organization_ids": ["org_pdt_partners", "org_cubist_systematic_strategies", "org_millennium_management"],
        "categories": ["Statistical arbitrage", "Pairs trading", "Mean reversion"],
        "market": "Equities",
        "asset_class": "Equity",
        "timeframe": "days",
        "core_edge": "STATISTICAL",
        "signal": ptext(
            "Cointegration / residual z-score vs peer basket or factor model; trade dislocations.",
            "STRONGLY_SUPPORTED",
        ),
        "entry": ptext("Enter when residual z-score exceeds entry threshold.", "CONFIRMED"),
        "exit": ptext("Exit at mean reversion / time stop / stop-loss on residual.", "CONFIRMED"),
        "position_sizing": ptext("Dollar or beta neutrality; volatility-scaled legs.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Factor neutrality, hard loss limits, borrow constraints.", "STRONGLY_SUPPORTED"),
        "hedging": ptext("Long-short residual portfolios; market beta hedged.", "CONFIRMED"),
        "execution": ptext("VWAP/TWAP/implementation shortfall algos.", "STRONGLY_SUPPORTED"),
        "automation": ptext("Typically highly automated.", "STRONGLY_SUPPORTED"),
        "data_requirements": ptext("Point-in-time fundamentals/prices, borrow, corporate actions.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(1.0, "ESTIMATED", "Academic pairs papers show attractive pre-cost Sharpes; live net UNKNOWN"),
            years_operating=pv(25, "ESTIMATED"),
            max_drawdown=pv(None, "UNKNOWN"),
        ),
        "edge_score": 70,
        "quality_score": 74,
        "reproducibility_score": 70,
        "implementation_difficulty": 6,
        "regime_dependency_score": 60,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_gatev_pairs_trading", "src_avellaneda_lee_statarb"],
        "research_interest": 88,
    },
    {
        "id": "strat_value_factor",
        "name": "Equity Value Factor (Book-to-Market / Multi-value)",
        "organization_ids": ["org_aqr_capital_management", "org_dimensional_fund_advisors_factor", "org_robeco_quantitative_investments"],
        "categories": ["Relative value", "Low frequency"],
        "market": "Global equities",
        "asset_class": "Equity",
        "timeframe": "months",
        "core_edge": "BEHAVIORAL",
        "signal": ptext("Cheap vs expensive on value metrics (B/M, E/P, CF/P composites).", "CONFIRMED"),
        "entry": ptext("Periodic rebalance into value quantile / score-weighted book.", "CONFIRMED"),
        "exit": ptext("Exit when valuation scores normalize relative to universe.", "CONFIRMED"),
        "position_sizing": ptext("Score or equal weight; industry neutralization common.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Tracking error budgets for long-only; leverage limits for L/S.", "STRONGLY_SUPPORTED"),
        "hedging": ptext("Long-short or long-only benchmark-relative.", "CONFIRMED"),
        "execution": ptext("Low turnover relative to HFT; patient rebalance.", "CONFIRMED"),
        "automation": ptext("Systematic.", "CONFIRMED"),
        "data_requirements": ptext("Point-in-time fundamentals; careful delisting treatment.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(0.3, "ESTIMATED", "Long-run value premium debated; recent decade weak in US"),
            years_operating=pv(40, "ESTIMATED"),
            crisis_performance=pv("Cyclical; value underperformed growth for long stretches post-2010s", "CONFIRMED"),
        ),
        "edge_score": 55,
        "quality_score": 70,
        "reproducibility_score": 90,
        "implementation_difficulty": 3,
        "regime_dependency_score": 80,
        "evidence_level": "CONFIRMED",
        "public_sources": ["src_fama_french_1992", "src_aqr_value_investing"],
        "research_interest": 75,
    },
    {
        "id": "strat_merger_arbitrage",
        "name": "Merger / Risk Arbitrage",
        "organization_ids": ["org_paulson_co_merger_arbitrage_lineage", "org_davidson_kempner", "org_magnetar_capital"],
        "categories": ["Merger arbitrage", "Event driven", "Arbitrage"],
        "market": "Announced M&A equities",
        "asset_class": "Equity",
        "timeframe": "weeks",
        "core_edge": "INFORMATION",
        "signal": ptext("Deal spread vs estimated completion probability and timing.", "CONFIRMED"),
        "entry": ptext("Long target / short acquirer (stock deals) when spread compensates for break risk.", "CONFIRMED"),
        "exit": ptext("Deal close, deal break, or spread compression to target.", "CONFIRMED"),
        "position_sizing": ptext("Conviction × capital at risk; hard caps per deal.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Deal-break scenarios, regulatory risk, financing risk, portfolio deal correlation.", "CONFIRMED"),
        "hedging": ptext("Cash deals: long target; stock deals: hedge acquirer.", "CONFIRMED"),
        "execution": ptext("Cash equity with borrow management.", "CONFIRMED"),
        "automation": ptext("Semi-systematic overlays; human deal assessment still central at most funds.", "STRONGLY_SUPPORTED"),
        "data_requirements": ptext("Deal terms databases, regulatory calendars, option-implied break odds.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(0.8, "ESTIMATED", "Classic merger arb Sharpe often cited moderate with low vol"),
            years_operating=pv(40, "ESTIMATED"),
            max_drawdown=pv(None, "UNKNOWN", "2008 and deal-break clusters painful"),
        ),
        "edge_score": 68,
        "quality_score": 72,
        "reproducibility_score": 55,
        "implementation_difficulty": 5,
        "regime_dependency_score": 60,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_mitchell_pulvino_merger"],
        "research_interest": 78,
    },
    {
        "id": "strat_convertible_arb",
        "name": "Convertible Bond Arbitrage",
        "organization_ids": ["org_highbridge_capital_management", "org_canyon_partners_convertible"],
        "categories": ["Convertible arbitrage", "Volatility arbitrage", "Relative value"],
        "market": "Convertible bonds + equities + options",
        "asset_class": "Credit / Equity hybrid",
        "timeframe": "days",
        "core_edge": "PRICING",
        "signal": ptext("Cheap convert vs model fair value / implied vol vs hedge instruments.", "STRONGLY_SUPPORTED"),
        "entry": ptext("Long cheap convert, short delta hedge equity (and sometimes credit hedge).", "CONFIRMED"),
        "exit": ptext("Richening to fair value, vol realization, or forced deleveraging.", "STRONGLY_SUPPORTED"),
        "position_sizing": ptext("Leverage common historically; risk in gamma/credit/liquidity.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Liquidity risk critical (2005/2008 lessons); haircuts, funding.", "CONFIRMED"),
        "hedging": ptext("Dynamic delta; credit and interest-rate hedges.", "CONFIRMED"),
        "execution": ptext("OTC convert markets + exchange equity hedges.", "CONFIRMED"),
        "automation": ptext("Pricing engines automated; risk overlays semi-automated.", "INFERRED"),
        "data_requirements": ptext("Convert terms, borrow, credit spreads, option surfaces.", "CONFIRMED"),
        "performance": _perf(
            years_operating=pv(30, "ESTIMATED"),
            crisis_performance=pv("Severe stress in 2008 due to leverage and liquidity", "CONFIRMED"),
            sharpe=pv(None, "UNKNOWN"),
        ),
        "edge_score": 60,
        "quality_score": 58,
        "reproducibility_score": 35,
        "implementation_difficulty": 8,
        "regime_dependency_score": 75,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_mitchell_pulvino_convert"],
        "research_interest": 70,
    },
    {
        "id": "strat_fx_carry",
        "name": "FX Carry Trade",
        "organization_ids": ["org_aqr_capital_management", "org_bridgewater_associates", "org_man_ahl"],
        "categories": ["Carry", "Macro", "Low frequency"],
        "market": "G10 / EM FX",
        "asset_class": "FX",
        "timeframe": "months",
        "core_edge": "STRUCTURAL",
        "signal": ptext("Long high-yielding currencies / short low-yielding; interest rate differential.", "CONFIRMED"),
        "entry": ptext("Rank currencies by carry; form long-short basket.", "CONFIRMED"),
        "exit": ptext("Rebalance on carry ranks; crash risk overlays sometimes added.", "STRONGLY_SUPPORTED"),
        "position_sizing": ptext("Vol targeting; crash-risk aware sizing recommended in literature.", "STRONGLY_SUPPORTED"),
        "risk_management": ptext("Carry crashes in risk-off; use trend/vol filters in research variants.", "CONFIRMED"),
        "hedging": ptext("Basket construction provides partial diversification.", "INFERRED"),
        "execution": ptext("Spot/forwards/futures; low frequency.", "CONFIRMED"),
        "automation": ptext("Easily automated.", "CONFIRMED"),
        "data_requirements": ptext("Interest rates, spot FX, rolls.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(0.4, "ESTIMATED"),
            crisis_performance=pv("Large negative in 2008-style risk-off", "CONFIRMED"),
            years_operating=pv(30, "ESTIMATED"),
        ),
        "edge_score": 58,
        "quality_score": 68,
        "reproducibility_score": 92,
        "implementation_difficulty": 2,
        "regime_dependency_score": 85,
        "evidence_level": "CONFIRMED",
        "public_sources": ["src_lustig_carry", "src_brunnermeier_carry_crash"],
        "research_interest": 80,
    },
    {
        "id": "strat_vol_risk_premium",
        "name": "Volatility Risk Premium / Short Volatility (Public Forms)",
        "organization_ids": ["org_capstone_investment_advisors", "org_susquehanna_international_group"],
        "categories": ["Volatility", "Options", "Volatility arbitrage"],
        "market": "Equity index options / VIX complex",
        "asset_class": "Volatility",
        "timeframe": "days",
        "core_edge": "PRICING",
        "signal": ptext("Implied vol rich vs expected realized; harvest premium via option structures.", "STRONGLY_SUPPORTED"),
        "entry": ptext("Sell options / variance when premium estimated positive after hedge costs.", "STRONGLY_SUPPORTED"),
        "exit": ptext("Expiry, buyback on rich-to-cheap flip, or risk limits.", "STRONGLY_SUPPORTED"),
        "position_sizing": ptext("Strict loss budgets; tail risk dominates.", "CONFIRMED"),
        "risk_management": ptext("Crash convexity; hedging with wings/variance; kill switches.", "CONFIRMED"),
        "hedging": ptext("Delta hedge; sometimes vega/correlation hedges.", "CONFIRMED"),
        "execution": ptext("Listed options; careful roll of short vol ETPs if used (retail forms fragile).", "STRONGLY_SUPPORTED"),
        "automation": ptext("Pricing/hedging automated; discretionary overlays common.", "INFERRED"),
        "data_requirements": ptext("Option surfaces, realized vol estimators.", "CONFIRMED"),
        "performance": _perf(
            sharpe=pv(None, "UNKNOWN", "Attractive until crash; path dependent"),
            crisis_performance=pv("Can suffer catastrophic losses (e.g., XIV Feb 2018 style events)", "CONFIRMED"),
            years_operating=pv(20, "ESTIMATED"),
        ),
        "edge_score": 62,
        "quality_score": 55,
        "reproducibility_score": 60,
        "implementation_difficulty": 7,
        "regime_dependency_score": 90,
        "evidence_level": "STRONGLY_SUPPORTED",
        "public_sources": ["src_bakshi_kapadia_vrp", "src_xiv_collapse_reports"],
        "research_interest": 84,
    },
]


def more_strategy_templates():
    """Additional strategy stubs expanded in build script to reach breadth targets."""
    return [
        ("strat_basis_cash_futures", "Equity Index Basis Trading", ["Basis trading", "Arbitrage"], "Equity index futures", "PRICING", 65),
        ("strat_funding_rate_arb_crypto", "Crypto Perp Funding Arbitrage", ["Funding arbitrage", "Arbitrage"], "Crypto perps/spot", "STRUCTURAL", 70),
        ("strat_order_flow_toxicity", "Order-Flow / Toxicity-Aware MM", ["Order-flow trading", "Market making", "High frequency"], "Equities", "SPEED", 80),
        ("strat_news_nlp_trading", "News/NLP Event Trading", ["News trading", "Sentiment", "Machine learning"], "Equities", "INFORMATION", 55),
        ("strat_alt_data_satellite", "Satellite/Alt-Data Demand Nowcasting", ["Alternative data", "Machine learning"], "Equities", "DATA", 60),
        ("strat_index_arb_etf", "ETF Creation/Redemption Arb", ["Arbitrage", "Market making"], "ETFs", "STRUCTURAL", 75),
        ("strat_latency_arb_historical", "Historical Latency Arbitrage", ["High frequency", "Arbitrage"], "Multi-venue equities", "SPEED", 40),
        ("strat_dispersion_trading", "Index-Single Stock Vol Dispersion", ["Volatility arbitrage", "Options"], "Equity options", "PRICING", 66),
        ("strat_calendar_spread_futures", "Futures Calendar Spreads", ["Relative value", "Carry"], "Commodities/Rates", "STRUCTURAL", 58),
        ("strat_spoos_bonds_risk_parity", "Risk Parity / All-Weather Style", ["Macro", "Portfolio construction"], "Multi-asset", "PORTFOLIO_CONSTRUCTION", 70),
        ("strat_defensive_equity", "Low-Volatility / Defensive Equity", ["Low frequency", "Relative value"], "Equities", "RISK_MANAGEMENT", 63),
        ("strat_quality_factor", "Quality / Profitability Factor", ["Low frequency"], "Equities", "BEHAVIORAL", 64),
        ("strat_size_factor", "Size Factor", ["Low frequency"], "Equities", "BEHAVIORAL", 45),
        ("strat_accruals_anomaly", "Accruals Anomaly", ["Low frequency", "Alternative data"], "Equities", "STATISTICAL", 50),
        ("strat_post_earnings_drift", "Post-Earnings Announcement Drift", ["Event driven", "Momentum"], "Equities", "BEHAVIORAL", 58),
        ("strat_short_interest_squeeze_avoid", "Short Interest / Crowding Signals", ["Sentiment", "Alternative data"], "Equities", "DATA", 52),
        ("strat_options_skew_rv", "Options Skew Relative Value", ["Options", "Volatility arbitrage"], "Equity options", "PRICING", 67),
        ("strat_fixed_income_rv", "Fixed Income Relative Value", ["Relative value"], "Rates/bonds", "PRICING", 72),
        ("strat_mortgage_basis", "Mortgage Basis / TBA Strategies", ["Relative value", "Basis trading"], "Rates", "STRUCTURAL", 55),
        ("strat_stat_arb_crypto", "Crypto Cross-Exchange Stat Arb", ["Statistical arbitrage", "Arbitrage"], "Crypto", "EXECUTION", 68),
        ("strat_triangle_arb_crypto", "Crypto Triangular Arbitrage", ["Arbitrage", "High frequency"], "Crypto", "SPEED", 35),
        ("strat_mean_reversion_intraday", "Intraday Mean Reversion Equities", ["Mean reversion"], "Equities", "STATISTICAL", 57),
        ("strat_opening_range_breakout", "Opening Range Breakout (Documented CTA/Discretionary)", ["Momentum", "Trend following"], "Futures/Equities", "BEHAVIORAL", 48),
        ("strat_turtle_trend", "Turtle Trading Rules (Public)", ["Trend following"], "Futures", "BEHAVIORAL", 60),
        ("strat_dual_momentum", "Dual Momentum (Gary Antonacci Public)", ["Momentum"], "Equities/ETFs", "BEHAVIORAL", 62),
        ("strat_end_of_month_seasonality", "Turn-of-Month Seasonality", ["Low frequency"], "Equities", "STATISTICAL", 40),
        ("strat_index_rebalance_arb", "Index Rebalance / Addition Trading", ["Event driven", "Arbitrage"], "Equities", "STRUCTURAL", 58),
        ("strat_spoofing_detection_avoid", "Manipulation-Aware Execution Filters", ["Execution", "High frequency"], "Equities", "TECHNOLOGY", 50),
        ("strat_rl_execution", "RL for Optimal Execution (Academic)", ["Reinforcement learning", "Execution"], "Equities", "TECHNOLOGY", 45),
        ("strat_finrl_portfolio", "FinRL-Style Deep RL Portfolio (Open Research)", ["Deep learning", "Reinforcement learning"], "Equities", "STATISTICAL", 42),
        ("strat_numerai_meta_model", "Numerai Crowdsourced Meta-Model", ["Machine learning", "Crowdsourced signals"], "Equities", "DATA", 66),
        ("strat_worldquant_alphas", "WorldQuant BRAIN Style Alphas", ["Statistical arbitrage", "Machine learning"], "Equities", "STATISTICAL", 70),
        ("strat_clenow_momentum", "Clenow Stocks on the Move Momentum", ["Momentum"], "Equities", "BEHAVIORAL", 65),
        ("strat_carver_sksys", "Carver Leveraged Systematic Futures", ["Trend following", "Carry"], "Futures", "PORTFOLIO_CONSTRUCTION", 74),
        ("strat_ernie_chan_mr", "Ernie Chan Mean-Reversion Recipes (Public Books)", ["Mean reversion", "Statistical arbitrage"], "Equities/ETFs", "STATISTICAL", 63),
        ("strat_hummingbot_mm", "Hummingbot Pure Market Making", ["Market making", "Liquidity provision"], "Crypto", "LIQUIDITY", 50),
        ("strat_hummingbot_avellaneda", "Hummingbot Avellaneda-Stoikov MM", ["Market making"], "Crypto", "PRICING", 58),
        ("strat_freqtrade_roi_stoploss", "Freqtrade Indicator + ROI/Stoploss Bots", ["Momentum", "Mean reversion"], "Crypto", "STATISTICAL", 35),
        ("strat_funding_basis_cash_carry_crypto", "Crypto Cash-and-Carry", ["Basis trading", "Carry"], "Crypto", "STRUCTURAL", 72),
        ("strat_jump_crypto_mm", "Crypto Exchange MM / Arb Desks (Public Characterization)", ["Market making", "Arbitrage"], "Crypto", "EXECUTION", 77),
        ("strat_wintermute_otc_mm", "Crypto OTC + Exchange MM", ["Market making", "Liquidity provision"], "Crypto", "LIQUIDITY", 73),
        ("strat_brevan_macro_rv", "Macro Relative Value (Public HF Characterization)", ["Macro", "Relative value"], "Rates/FX", "INFORMATION", 70),
        ("strat_bridgewater_risk_parity", "Bridgewater All Weather / Risk Parity Style", ["Macro", "Portfolio construction"], "Multi-asset", "PORTFOLIO_CONSTRUCTION", 76),
        ("strat_two_sigma_ml_equity", "Two Sigma Style ML Equity (Public Characterization)", ["Machine learning", "Statistical arbitrage"], "Equities", "DATA", 82),
        ("strat_de_shaw_stat_arb", "D.E. Shaw Computational/Stat Arb Characterization", ["Statistical arbitrage", "Machine learning"], "Multi-asset", "STATISTICAL", 86),
        ("strat_jane_street_etf_arb", "ETF / Closed-End Relative Value MM", ["Arbitrage", "Market making"], "ETFs", "PRICING", 84),
        ("strat_sig_options_mm", "SIG-Style Options Market Making", ["Options", "Market making"], "Options", "PRICING", 83),
        ("strat_citadel_multi_strat", "Citadel Multi-Strategy Aggregation", ["Statistical arbitrage", "Macro", "Event driven"], "Multi-asset", "PORTFOLIO_CONSTRUCTION", 88),
        ("strat_millennium_pod", "Pod-Shop Idiosyncratic Alpha Aggregation", ["Statistical arbitrage", "Event driven"], "Equities", "PORTFOLIO_CONSTRUCTION", 80),
        ("strat_g_research_ml", "G-Research Style Predictive Modeling (Public Job/Research Characterization)", ["Machine learning", "Statistical arbitrage"], "Equities", "STATISTICAL", 78),
        ("strat_cf_m_physics", "CFM Physics-Inspired Quant Strategies (Public Characterization)", ["Statistical arbitrage", "Machine learning"], "Multi-asset", "STATISTICAL", 79),
        ("strat_systematica_trend", "Systematica BlueTrend Style", ["Trend following"], "Futures", "BEHAVIORAL", 76),
        ("strat_lyn_x_trend", "Lynx Trend Following", ["Trend following"], "Futures", "BEHAVIORAL", 74),
        ("strat_isam_trend", "ISAM Systematic Trend", ["Trend following"], "Futures", "BEHAVIORAL", 73),
        ("strat_quest_short_term", "Quest Partners Short-Term Trend/Crisis Style", ["Trend following", "Macro"], "Futures", "RISK_MANAGEMENT", 71),
        ("strat_dunn_aggressive_trend", "Dunn Capital Aggressive Trend", ["Trend following"], "Futures", "BEHAVIORAL", 68),
        ("strat_winton_diversified", "Winton Diversified Trend/Quant", ["Trend following", "Machine learning"], "Futures", "STATISTICAL", 77),
        ("strat_aspect_diversified", "Aspect Diversified Program Style", ["Trend following"], "Futures", "BEHAVIORAL", 75),
        ("strat_transtrend_dtp", "Transtrend Diversified Trend Program", ["Trend following"], "Futures", "BEHAVIORAL", 76),
        ("strat_ahl_dimension", "Man AHL Dimension / Evolution Style", ["Trend following", "Machine learning"], "Futures", "STATISTICAL", 81),
        ("strat_numeric_equity", "Man Numeric / Equity Market Neutral Style", ["Statistical arbitrage", "Cross-sectional momentum"], "Equities", "STATISTICAL", 74),
        ("strat_arrowstreet_global", "Arrowstreet Global Equity Alpha", ["Machine learning", "Cross-sectional momentum"], "Equities", "STATISTICAL", 76),
        ("strat_acadian_em", "Acadian Systematic Equity", ["Cross-sectional momentum", "Machine learning"], "Equities", "STATISTICAL", 72),
        ("strat_panagora_risk_parity", "PanAgora Risk Parity / Equity Market Neutral", ["Portfolio construction", "Statistical arbitrage"], "Equities", "PORTFOLIO_CONSTRUCTION", 70),
        ("strat_voleon_ml", "Voleon ML Trading Characterization", ["Machine learning", "Deep learning"], "Equities", "DATA", 80),
        ("strat_rebellion_ai", "Rebellion Research AI Allocation", ["Machine learning"], "Equities", "DATA", 48),
        ("strat_high_flyer_china", "High-Flyer China ML Quant", ["Machine learning", "Deep learning"], "China equities", "DATA", 78),
        ("strat_ubiquant_china", "Ubiquant Quantitative Strategies", ["Statistical arbitrage", "Machine learning"], "China equities", "STATISTICAL", 77),
        ("strat_xtx_ml_mm", "XTX ML Market Making Characterization", ["Market making", "Machine learning", "High frequency"], "Multi-asset", "TECHNOLOGY", 87),
        ("strat_hrt_hft", "HRT HFT Liquidity Provision", ["High frequency", "Market making"], "Equities/Futures", "SPEED", 86),
        ("strat_jump_hft", "Jump Trading HFT / Research Characterization", ["High frequency", "Arbitrage"], "Multi-asset", "SPEED", 87),
        ("strat_tower_hft", "Tower Research HFT", ["High frequency"], "Multi-asset", "SPEED", 82),
        ("strat_optiver_options", "Optiver Options Pricing MM", ["Options", "Market making"], "Options", "PRICING", 85),
        ("strat_imc_mm", "IMC Market Making", ["Market making", "Options"], "Multi-asset", "EXECUTION", 84),
        ("strat_flow_etf", "Flow Traders ETF MM", ["Market making", "Arbitrage"], "ETFs", "STRUCTURAL", 80),
        ("strat_drw_crypto_cumberland", "Cumberland / DRW Crypto Liquidity", ["Market making", "Liquidity provision"], "Crypto", "LIQUIDITY", 74),
        ("strat_qcp_options_crypto", "QCP Crypto Options", ["Options", "Volatility"], "Crypto options", "PRICING", 68),
        ("strat_gsr_crypto", "GSR Crypto Trading / MM", ["Market making", "Arbitrage"], "Crypto", "EXECUTION", 67),
        ("strat_amber_crypto", "Amber Group Crypto Quant/MM", ["Market making", "Arbitrage"], "Crypto", "EXECUTION", 66),
        ("strat_kronos_crypto", "Kronos Research Crypto Quant", ["Statistical arbitrage", "High frequency"], "Crypto", "SPEED", 65),
        ("strat_selini_crypto", "Selini Capital Crypto MM", ["Market making"], "Crypto", "LIQUIDITY", 60),
        ("strat_pead_options", "Earnings Announcement Options Strategies", ["Event driven", "Options"], "Equity options", "INFORMATION", 57),
        ("strat_pin_risk_options", "Pin Risk / Expiry Microstructure", ["Options", "High frequency"], "Equity options", "STRUCTURAL", 50),
        ("strat_gamma_scalping", "Long Gamma Scalping", ["Volatility", "Options"], "Equity options", "PRICING", 55),
        ("strat_variance_swap_rv", "Variance Swap / Realized Var Trading", ["Volatility arbitrage"], "Equity index", "PRICING", 64),
        ("strat_correlation_trading", "Correlation / Dispersion Trading Extended", ["Volatility arbitrage"], "Equity options", "PRICING", 63),
        ("strat_capital_structure_arb", "Capital Structure Arbitrage", ["Relative value", "Event driven"], "Credit/Equity", "PRICING", 58),
        ("strat_spa_c_arb_historical", "SPAC Arb (Historical Crowding Caution)", ["Event driven", "Arbitrage"], "Equities", "STRUCTURAL", 30),
        ("strat_closed_end_fund_arb", "Closed-End Fund Discount Arb", ["Relative value", "Arbitrage"], "Equities/CEFs", "BEHAVIORAL", 52),
        ("strat_adr_arb", "ADR / Local Share Arbitrage", ["Arbitrage"], "Equities", "STRUCTURAL", 48),
        ("strat_tax_aware_factor", "Tax-Aware Factor Harvesting", ["Low frequency", "Portfolio construction"], "Equities", "STRUCTURAL", 55),
        ("strat_liquidity_provision_dark", "Dark Pool / Midpoint Liquidity Strategies", ["Liquidity provision", "Execution"], "Equities", "EXECUTION", 50),
        ("strat_tca_alpha", "TCA / Implementation Shortfall Minimization as Edge", ["Execution"], "Equities", "EXECUTION", 60),
        ("strat_borrow_specials", "Hard-to-Borrow Specials Trading", ["Relative value"], "Equities", "STRUCTURAL", 58),
        ("strat_etf_flow_prediction", "ETF Flow Prediction Strategies", ["Alternative data", "Event driven"], "Equities/ETFs", "DATA", 56),
        ("strat_credit_momentum", "Credit Momentum / CDS", ["Momentum", "Relative value"], "Credit", "BEHAVIORAL", 57),
        ("strat_commodity_carry_roll", "Commodity Roll / Curve Carry", ["Carry", "Basis trading"], "Commodities", "STRUCTURAL", 66),
        ("strat_commodity_tsmom", "Commodity Time-Series Momentum", ["Trend following", "Momentum"], "Commodities", "BEHAVIORAL", 72),
        ("strat_equity_index_tsmom", "Equity Index Time-Series Momentum", ["Trend following", "Momentum"], "Equity indices", "BEHAVIORAL", 74),
        ("strat_bond_tsmom", "Bond Time-Series Momentum", ["Trend following"], "Rates", "BEHAVIORAL", 70),
        ("strat_fx_tsmom", "FX Time-Series Momentum", ["Trend following"], "FX", "BEHAVIORAL", 71),
        ("strat_multi_asset_tsmom", "Moskowitz-Style Multi-Asset TSMOM", ["Trend following", "Momentum"], "Multi-asset", "BEHAVIORAL", 82),
        ("strat_risk_premia_stack", "Multi-Style Risk Premia Stack", ["Momentum", "Value", "Carry", "Portfolio construction"], "Multi-asset", "PORTFOLIO_CONSTRUCTION", 80),
        ("strat_defensive_momentum", "Momentum with Volatility Filter", ["Momentum", "Risk management"], "Equities", "RISK_MANAGEMENT", 73),
        ("strat_trend_with_carry", "Trend + Carry Combination (Public Research)", ["Trend following", "Carry"], "Futures/FX", "PORTFOLIO_CONSTRUCTION", 77),
    ]
