"""
Curated discovery universe for Hedge Fund Alpha Atlas.

All entries are organizations/systems known from public discourse.
Performance fields are intentionally sparse — filled only when public
evidence exists; otherwise UNKNOWN.
"""

from __future__ import annotations

# Famous / starting-point funds (Phase 2) — detailed later in FAMOUS_DETAILS
FAMOUS_SEEDS = [
    ("Renaissance Technologies", "quant_hf", 1982, "USA", "famous"),
    ("D. E. Shaw & Co.", "quant_hf", 1988, "USA", "famous"),
    ("Two Sigma", "quant_hf", 2001, "USA", "famous"),
    ("Citadel", "multi_strat", 1990, "USA", "famous"),
    ("Citadel Securities", "market_maker", 2002, "USA", "famous"),
    ("Jane Street", "prop", 2000, "USA", "famous"),
    ("Jump Trading", "hft", 1999, "USA", "famous"),
    ("Hudson River Trading", "hft", 2002, "USA", "famous"),
    ("Virtu Financial", "market_maker", 2008, "USA", "famous"),
    ("Susquehanna International Group", "prop", 1987, "USA", "famous"),
    ("DRW", "prop", 1992, "USA", "famous"),
    ("Tower Research Capital", "hft", 1998, "USA", "famous"),
    ("WorldQuant", "quant_hf", 2007, "USA", "famous"),
    ("AQR Capital Management", "systematic_hf", 1998, "USA", "famous"),
    ("Man Group", "systematic_hf", 1783, "UK", "famous"),
    ("Millennium Management", "multi_strat", 1989, "USA", "famous"),
    ("Point72", "multi_strat", 2014, "USA", "famous"),
    ("Schonfeld Strategic Advisors", "multi_strat", 1988, "USA", "famous"),
    ("G-Research", "quant_hf", 2001, "UK", "famous"),
    ("Winton Group", "cta", 1997, "UK", "famous"),
    ("PDT Partners", "quant_hf", 1993, "USA", "famous"),
    ("Cubist Systematic Strategies", "quant_hf", 2007, "USA", "famous"),
]

QUANT_SYSTEMATIC = [
    ("Bridgewater Associates", "macro_quant", 1975, "USA", "famous"),
    ("TGS Management", "quant_hf", None, "USA", "specialist"),
    ("Qube Research & Technologies", "quant_hf", 2018, "UK", "known"),
    ("Squarepoint Capital", "quant_hf", 2014, "UK", "known"),
    ("Marshall Wace", "systematic_hf", 1997, "UK", "known"),
    ("Systematica Investments", "systematic_hf", 2015, "Switzerland", "known"),
    ("CFM (Capital Fund Management)", "quant_hf", 1991, "France", "known"),
    ("Quest Partners", "cta", 2001, "USA", "specialist"),
    ("Aspect Capital", "cta", 1997, "UK", "known"),
    ("Transtrend", "cta", 1991, "Netherlands", "known"),
    ("Campbell & Company", "cta", 1972, "USA", "known"),
    ("Graham Capital Management", "cta", 1994, "USA", "known"),
    ("ISAM", "cta", 2001, "UK", "known"),
    ("Lynx Asset Management", "cta", 1999, "Sweden", "known"),
    ("AHL (Man AHL)", "cta", 1987, "UK", "famous"),
    ("Numeric Investors", "systematic_hf", 1989, "USA", "known"),
    ("Acadian Asset Management", "systematic_hf", 1987, "USA", "known"),
    ("PanAgora Asset Management", "systematic_hf", 1985, "USA", "known"),
    ("Invesco Quantitative Strategies", "systematic_hf", None, "USA", "known"),
    ("Arrowstreet Capital", "systematic_hf", 1999, "USA", "known"),
    ("Lateral Investment Management", "quant_hf", None, "USA", "emerging"),
    ("Voleon Group", "ml_trading", 2007, "USA", "known"),
    ("Rebellion Research", "ml_trading", 2007, "USA", "specialist"),
    ("Walnut Algorithms", "ml_trading", None, "France", "emerging"),
    ("Quantica Capital", "cta", 2003, "Switzerland", "specialist"),
    ("Crabel Capital Management", "cta", 1987, "USA", "known"),
    ("Dunn Capital Management", "cta", 1974, "USA", "known"),
    ("Mulvaney Capital Management", "cta", 1999, "UK", "specialist"),
    ("Eclipse Capital Management", "cta", 2000, "USA", "specialist"),
    ("Abraham Trading Company", "cta", 1977, "USA", "specialist"),
    ("Chesapeake Capital", "cta", 1988, "USA", "known"),
    ("Sunrise Capital Partners", "cta", 1980, "USA", "specialist"),
    ("Altis Partners", "cta", 2001, "Monaco", "specialist"),
    ("Estlander & Partners", "cta", 1991, "Finland", "specialist"),
    ("RPM Risk & Portfolio Management", "cta", 1993, "Sweden", "specialist"),
    ("SEB Asset Management Quant", "systematic_hf", None, "Sweden", "known"),
    ("Nordea Quantitative Strategies", "systematic_hf", None, "Denmark", "known"),
    ("Robeco Quantitative Investments", "systematic_hf", 1929, "Netherlands", "known"),
    ("QMA (PGIM Quantitative)", "systematic_hf", 1975, "USA", "known"),
    ("GSAM Quantitative Investment Strategies", "systematic_hf", None, "USA", "known"),
    ("BlackRock Systematic", "systematic_hf", None, "USA", "famous"),
    ("J.P. Morgan Quantitative Solutions", "systematic_hf", None, "USA", "known"),
    ("UBS Systematic Alpha", "systematic_hf", None, "Switzerland", "known"),
    ("BNP Paribas Quantitative Research", "algo_company", None, "France", "known"),
    ("Société Générale Cross Asset Research Quant", "algo_company", None, "France", "known"),
    ("Barclays Quantitative Portfolio Strategy", "algo_company", None, "UK", "known"),
]

PROP_HFT_MM = [
    ("Optiver", "market_maker", 1986, "Netherlands", "famous"),
    ("IMC Trading", "market_maker", 1989, "Netherlands", "famous"),
    ("Flow Traders", "market_maker", 2004, "Netherlands", "known"),
    ("Akuna Capital", "options", 2011, "USA", "known"),
    ("Belvedere Trading", "prop", 2002, "USA", "known"),
    ("Peak6", "options", 1997, "USA", "known"),
    ("CTC (Chicago Trading Company)", "options", 1995, "USA", "known"),
    ("Maven Securities", "prop", 2011, "UK", "known"),
    ("XTX Markets", "market_maker", 2015, "UK", "famous"),
    ("GSA Capital", "quant_hf", 2005, "UK", "known"),
    ("Teza Technologies", "hft", 2009, "USA", "known"),
    ("Headlands Technologies", "hft", 2009, "USA", "specialist"),
    ("Radix Trading", "hft", 2012, "USA", "specialist"),
    ("Sun Trading", "prop", 2002, "USA", "specialist"),
    ("Allston Trading", "hft", 2002, "USA", "specialist"),
    ("Spot Trading", "prop", 1999, "USA", "specialist"),
    ("Wolverine Trading", "prop", 1994, "USA", "known"),
    ("Group One Trading", "market_maker", 2001, "USA", "specialist"),
    ("Simplex Trading", "options", 2004, "USA", "specialist"),
    ("Hard Eight Futures", "prop", None, "USA", "emerging"),
    ("Five Rings Capital", "prop", None, "USA", "specialist"),
    ("Old Mission Capital", "prop", 2009, "USA", "known"),
    ("Jump Crypto", "crypto_hf", 2021, "USA", "known"),
    ("Wintermute", "crypto_hf", 2017, "UK", "known"),
    ("Alameda Research", "crypto_hf", 2017, "USA", "known"),  # historical; failure case
    ("Cumberland DRW", "crypto_hf", 2014, "USA", "known"),
    ("Genesis Trading Desk", "crypto_hf", None, "USA", "specialist"),
    ("B2C2", "crypto_hf", 2015, "UK", "specialist"),
    ("GSR Markets", "crypto_hf", 2013, "Hong Kong", "specialist"),
    ("Amber Group", "crypto_hf", 2017, "Singapore", "known"),
    ("DV Trading", "prop", 2014, "USA", "known"),
    ("Eagle Seven", "prop", 2008, "USA", "specialist"),
    ("TransMarket Group", "prop", 1980, "USA", "known"),
    ("HTG Capital Partners", "hft", None, "USA", "emerging"),
    ("Viborne Capital", "hft", None, "USA", "emerging"),
    ("Quantlab", "hft", 1998, "USA", "known"),
    ("Tradebot Systems", "hft", 1999, "USA", "specialist"),
    ("Getco", "hft", 1999, "USA", "known"),  # merged into KCG/Virtu lineage
    ("KCG Holdings", "market_maker", 2013, "USA", "known"),
    ("Citadel Global Equities", "quant_hf", None, "USA", "famous"),
    ("Renaissance Medallion", "quant_hf", 1988, "USA", "famous"),
    ("Renaissance Institutional Equities Fund", "quant_hf", 2005, "USA", "famous"),
]

MULTI_STRAT_POD = [
    ("Balyasny Asset Management", "multi_strat", 2001, "USA", "known"),
    ("ExodusPoint Capital Management", "multi_strat", 2017, "USA", "known"),
    ("Farallon Capital", "multi_strat", 1986, "USA", "known"),
    ("Elliott Management", "multi_strat", 1977, "USA", "famous"),
    ("Third Point", "multi_strat", 1995, "USA", "known"),
    ("Pershing Square", "multi_strat", 2004, "USA", "known"),
    ("Appaloosa Management", "multi_strat", 1993, "USA", "known"),
    ("Viking Global Investors", "multi_strat", 1999, "USA", "known"),
    ("Tiger Global Management", "multi_strat", 2001, "USA", "known"),
    ("Coatue Management", "multi_strat", 1999, "USA", "known"),
    ("Lone Pine Capital", "multi_strat", 1997, "USA", "known"),
    ("Mavernick Capital", "multi_strat", 2015, "USA", "emerging"),
    ("Verition Fund Management", "multi_strat", 2008, "USA", "known"),
    ("Boothbay Fund Management", "multi_strat", 2011, "USA", "specialist"),
    ("Walleye Capital", "multi_strat", 2005, "USA", "known"),
    ("HBK Capital Management", "multi_strat", 1991, "USA", "known"),
    ("Magnetar Capital", "multi_strat", 2005, "USA", "known"),
    ("Citadel Tactical Trading", "multi_strat", None, "USA", "famous"),
    ("DE Shaw Composite Fund", "quant_hf", None, "USA", "famous"),
    ("Two Sigma Spectrum", "quant_hf", None, "USA", "famous"),
    ("Two Sigma Absolute Return", "quant_hf", None, "USA", "famous"),
    ("Man GLG", "multi_strat", 1995, "UK", "known"),
    ("Man Numeric", "systematic_hf", None, "USA", "known"),
    ("Winton Trend", "cta", None, "UK", "known"),
    ("Aspect Diversified Trends", "cta", None, "UK", "known"),
]

CRYPTO_AND_DIGITAL = [
    ("Pantera Capital", "crypto_hf", 2013, "USA", "known"),
    ("Polychain Capital", "crypto_hf", 2016, "USA", "known"),
    ("Multicoin Capital", "crypto_hf", 2017, "USA", "known"),
    ("Paradigm", "crypto_hf", 2018, "USA", "known"),
    ("a16z crypto", "crypto_hf", 2018, "USA", "known"),
    ("Galaxy Digital Trading", "crypto_hf", 2018, "USA", "known"),
    ("Three Arrows Capital", "crypto_hf", 2012, "Singapore", "known"),  # failure case
    ("Bitwise Asset Management", "crypto_hf", 2017, "USA", "known"),
    ("Grayscale Investments", "crypto_hf", 2013, "USA", "known"),
    ("CoinShares", "crypto_hf", 2013, "UK", "known"),
    ("Adaptive Fund", "crypto_hf", None, "UNKNOWN", "emerging"),
    ("QCP Capital", "crypto_hf", 2017, "Singapore", "specialist"),
    ("Modular Asset Management", "crypto_hf", None, "UNKNOWN", "emerging"),
    ("Nascent", "crypto_hf", 2018, "USA", "specialist"),
    ("Delphi Ventures Trading", "crypto_hf", None, "USA", "specialist"),
    ("Framework Ventures Trading Desk", "crypto_hf", None, "USA", "specialist"),
    ("CMS Holdings", "crypto_hf", 2019, "USA", "specialist"),
    ("Splinter Capital", "crypto_hf", None, "UNKNOWN", "emerging"),
    ("Selini Capital", "crypto_hf", 2021, "Singapore", "emerging"),
    ("FalconX Trading", "crypto_hf", 2018, "USA", "known"),
    ("Hidden Road Partners", "crypto_hf", 2019, "USA", "specialist"),
    ("Kronos Research", "crypto_hf", 2018, "Taiwan", "specialist"),
    ("Java Trading Co Crypto", "crypto_hf", None, "USA", "emerging"),
    ("Tower Research Crypto", "crypto_hf", None, "USA", "known"),
    ("Jane Street Digital Assets", "prop", None, "USA", "famous"),
]

ASIA_EUROPE_SPECIALISTS = [
    ("Abraxas Capital Management", "cta", None, "UK", "specialist"),
    ("BlueCrest Capital Management", "multi_strat", 2000, "UK", "known"),
    ("Brevan Howard", "macro_quant", 2002, "UK", "famous"),
    ("Caxton Associates", "macro_quant", 1983, "USA", "known"),
    ("Rokos Capital Management", "macro_quant", 2015, "UK", "known"),
    ("The Children's Investment Fund", "multi_strat", 2003, "UK", "known"),
    ("Egerton Capital", "multi_strat", 1994, "UK", "known"),
    ("Lansdowne Partners", "multi_strat", 1998, "UK", "known"),
    ("Marshall Street Capital", "quant_hf", None, "UNKNOWN", "emerging"),
    ("Haitong Quantitative", "quant_hf", None, "China", "specialist"),
    ("Ubiquant Investment", "quant_hf", 2012, "China", "known"),
    ("High-Flyer Quant", "ml_trading", 2015, "China", "known"),
    ("Mingshi Investment", "quant_hf", None, "China", "specialist"),
    ("Rhine Asset Management", "quant_hf", None, "China", "emerging"),
    ("Miyoshi Asset Management", "quant_hf", None, "Japan", "emerging"),
    ("Simplex Asset Management Japan", "systematic_hf", 1999, "Japan", "specialist"),
    ("Sparx Group Quant", "systematic_hf", None, "Japan", "specialist"),
    ("Nomura Quant Strategies", "systematic_hf", None, "Japan", "known"),
    ("Samsung Asset Management Quant", "systematic_hf", None, "South Korea", "specialist"),
    ("Kiwoom Quantitative", "quant_hf", None, "South Korea", "emerging"),
    ("Tower Research Europe", "hft", None, "UK", "known"),
    ("Optiver Asia Pacific", "market_maker", None, "Australia", "known"),
    ("IMC Asia", "market_maker", None, "Hong Kong", "known"),
    ("Jane Street Asia", "prop", None, "Hong Kong", "famous"),
    ("Akuna Asia", "options", None, "Australia", "known"),
    ("Maven Asia", "prop", None, "Hong Kong", "specialist"),
    ("XTX Asia", "market_maker", None, "Singapore", "known"),
    ("GSA Asia", "quant_hf", None, "Asia", "specialist"),
    ("Qube Asia", "quant_hf", None, "Asia", "emerging"),
    ("Squarepoint Asia", "quant_hf", None, "Singapore", "known"),
]

ALT_DATA_ML_ACADEMIC = [
    ("ExtractAlpha", "alt_data", 2013, "USA", "specialist"),
    ("Eagle Alpha", "alt_data", 2012, "Ireland", "specialist"),
    ("AlternativeData.org Research Collective", "alt_data", None, "USA", "academic"),
    ("Orbital Insight Trading Research", "alt_data", 2013, "USA", "specialist"),
    ("RS Metrics", "alt_data", 2009, "USA", "specialist"),
    ("Thinknum Alternative Data", "alt_data", 2014, "USA", "specialist"),
    ("YipitData", "alt_data", 2008, "USA", "specialist"),
    ("Earnest Research", "alt_data", 2012, "USA", "specialist"),
    ("Second Measure", "alt_data", 2015, "USA", "specialist"),
    ("Premonition.io", "alt_data", None, "USA", "emerging"),
    ("Numerai", "ml_trading", 2015, "USA", "known"),
    ("Quantopian Legacy Community Strategies", "open_source", 2011, "USA", "known"),
    ("WorldQuant BRAIN", "quant_hf", 2015, "USA", "known"),
    ("QuantConnect Community", "open_source", 2012, "USA", "known"),
    ("Lean Engine Ecosystem", "open_source", 2012, "USA", "known"),
    ("Zipline / PyFolio Research Stack", "open_source", 2012, "USA", "known"),
    ("Backtrader Community", "open_source", 2015, "UNKNOWN", "open_source"),
    ("Freqtrade Community", "trading_bot", 2017, "UNKNOWN", "open_source"),
    ("Jesse Trade", "trading_bot", 2018, "UNKNOWN", "open_source"),
    ("Hummingbot", "trading_bot", 2019, "USA", "open_source"),
    ("OctoBot", "trading_bot", 2018, "UNKNOWN", "open_source"),
    ("Gekko Trading Bot", "trading_bot", 2014, "UNKNOWN", "open_source"),
    ("Zenbot", "trading_bot", 2016, "UNKNOWN", "open_source"),
    ("Tribeca Crypto Bot Frameworks", "trading_bot", None, "UNKNOWN", "emerging"),
    ("Stanford AI Lab Trading Papers", "academic", None, "USA", "academic"),
    ("MIT Laboratory for Financial Engineering", "academic", None, "USA", "academic"),
    ("Princeton Bendheim Center Trading Research", "academic", None, "USA", "academic"),
    ("Oxford Man Institute", "academic", 2007, "UK", "academic"),
    ("Cornell Financial Engineering Manhattan", "academic", None, "USA", "academic"),
    ("CMU Machine Learning Finance Group", "academic", None, "USA", "academic"),
    ("ETH Zurich Computational Finance", "academic", None, "Switzerland", "academic"),
    ("EPFL Financial Engineering", "academic", None, "Switzerland", "academic"),
    ("Imperial College Quantitative Finance", "academic", None, "UK", "academic"),
    ("LSE Systemic Risk / Quant Finance", "academic", None, "UK", "academic"),
    ("University of Chicago Booth Quant Research", "academic", None, "USA", "academic"),
]

INDEPENDENT_AND_DOCUMENTED_TRADERS = [
    ("Ernie Chan QTS Capital", "indie_trader", 2008, "USA", "known"),
    ("Andreas Clenow Following the Trend Desk", "indie_trader", None, "Switzerland", "specialist"),
    ("Robert Carver Systematic Trading", "indie_trader", None, "UK", "specialist"),
    ("Toby Crabel Research Lineage", "cta", 1987, "USA", "known"),
    ("Larry Hite Mint Investment Management lineage", "cta", 1981, "USA", "known"),
    ("Richard Dennis Turtle Traders lineage", "cta", 1983, "USA", "famous"),
    ("Ed Seykota Systems", "cta", None, "USA", "famous"),
    ("Bill Eckhardt Systems", "cta", None, "USA", "known"),
    ("Michael Covel Trend Following Research", "cta", None, "USA", "specialist"),
    ("David Harding Winton lineage", "cta", 1997, "UK", "famous"),
    ("Jim Simons Renaissance lineage", "quant_hf", 1982, "USA", "famous"),
    ("Peter Brown / Robert Mercer Medallion era", "quant_hf", None, "USA", "famous"),
    ("Cliff Asness AQR Factor Research", "systematic_hf", 1998, "USA", "famous"),
    ("AQR Momentum Factor Desk", "systematic_hf", None, "USA", "famous"),
    ("AQR Value Factor Desk", "systematic_hf", None, "USA", "famous"),
    ("AQR Defensive Equity Desk", "systematic_hf", None, "USA", "known"),
    ("Robeco Conservative Equities", "systematic_hf", None, "Netherlands", "known"),
    ("Dimensional Fund Advisors Factor", "systematic_hf", 1981, "USA", "famous"),
    ("Research Affiliates Smart Beta", "systematic_hf", 2002, "USA", "known"),
    ("TOBAM Maximum Diversification", "systematic_hf", 2005, "France", "specialist"),
    ("Intech Investment Management", "systematic_hf", 1987, "USA", "specialist"),
    ("LGT Capital Partners Quant", "systematic_hf", None, "Switzerland", "specialist"),
    ("Pictet Quant Equities", "systematic_hf", None, "Switzerland", "known"),
    ("Unigestion Quant", "systematic_hf", None, "Switzerland", "specialist"),
    ("Lombard Odier Quantitative", "systematic_hf", None, "Switzerland", "specialist"),
]

VOL_OPTIONS_EVENT = [
    ("Capstone Investment Advisors", "vol_trading", 2003, "USA", "known"),
    ("Assenagon Alpha Volatility", "vol_trading", None, "Germany", "specialist"),
    ("Parallax Volatility Advisers", "vol_trading", 1990, "USA", "specialist"),
    ("Ionic Capital Management", "vol_trading", 2006, "USA", "specialist"),
    ("Dominion Capital Management Vol", "vol_trading", None, "UNKNOWN", "emerging"),
    ("Pine River Capital Management", "relative_value", 2002, "USA", "known"),
    ("Canyon Partners Convertible", "multi_strat", 1990, "USA", "known"),
    ("Highbridge Capital Management", "multi_strat", 1992, "USA", "known"),
    ("Aristeia Capital", "multi_strat", 1997, "USA", "specialist"),
    ("Whitebox Advisors", "multi_strat", 1999, "USA", "specialist"),
    ("Saba Capital Management", "multi_strat", 2009, "USA", "known"),
    ("Aurelius Capital Management", "event_driven", 2005, "USA", "specialist"),
    ("Paulson & Co Merger Arbitrage lineage", "event_driven", 1994, "USA", "known"),
    ("Davidson Kempner", "event_driven", 1983, "USA", "known"),
    ("York Capital Management", "event_driven", 1991, "USA", "known"),
    ("Carlson Capital", "event_driven", 1993, "USA", "specialist"),
    ("Harbinger Capital (historical)", "event_driven", 2001, "USA", "known"),
    ("Appaloosa Credit Relative Value", "relative_value", None, "USA", "known"),
    ("BlueMountain Credit Alternatives", "relative_value", 2003, "USA", "known"),
    ("Ellington Management Group", "relative_value", 1994, "USA", "known"),
]

ADDITIONAL_PROP_AND_ALGO = [
    ("Jane Street ETF Desk", "prop", None, "USA", "famous"),
    ("Jane Street Options Desk", "options", None, "USA", "famous"),
    ("SIG Index Arb Desk", "prop", None, "USA", "famous"),
    ("SIG Volatility Desk", "vol_trading", None, "USA", "famous"),
    ("DRW Options Desk", "options", None, "USA", "known"),
    ("DRW Fixed Income Relative Value", "relative_value", None, "USA", "known"),
    ("Citadel Surveyor Fund", "quant_hf", None, "USA", "famous"),
    ("Citadel Equities", "quant_hf", None, "USA", "famous"),
    ("Millennium Equity Arbitrage Pods", "stat_arb", None, "USA", "famous"),
    ("Millennium Quantitative Pods", "quant_hf", None, "USA", "famous"),
    ("Point72 Cubist Pods", "quant_hf", None, "USA", "famous"),
    ("Schonfeld Fundamental Equities", "multi_strat", None, "USA", "known"),
    ("Schonfeld Quantitative Strategies", "quant_hf", None, "USA", "known"),
    ("Walleye Options Market Making", "options", None, "USA", "known"),
    ("Belvedere Options MM", "options", None, "USA", "known"),
    ("Akuna Volatility Arbitrage", "vol_trading", None, "USA", "known"),
    ("CTC Options MM", "options", None, "USA", "known"),
    ("Peak6 Volatility", "vol_trading", None, "USA", "known"),
    ("Flow Traders ETF MM", "market_maker", None, "Netherlands", "known"),
    ("Virtu ETF MM", "market_maker", None, "USA", "famous"),
    ("Virtu Customer Market Making", "market_maker", None, "USA", "famous"),
    ("Tower Futures HFT", "hft", None, "USA", "known"),
    ("HRT Equities HFT", "hft", None, "USA", "famous"),
    ("HRT Futures", "hft", None, "USA", "famous"),
    ("Jump Equities", "hft", None, "USA", "famous"),
    ("Jump Futures", "hft", None, "USA", "famous"),
    ("Jump Fixed Income", "hft", None, "USA", "known"),
    ("XTX Equities", "market_maker", None, "UK", "famous"),
    ("XTX FX", "market_maker", None, "UK", "famous"),
    ("Optiver Equity Options", "options", None, "Netherlands", "famous"),
    ("Optiver Pricing Engine Desk", "market_maker", None, "Netherlands", "famous"),
    ("IMC Options", "options", None, "Netherlands", "famous"),
    ("IMC ETF", "market_maker", None, "Netherlands", "known"),
]

OPEN_SOURCE_AND_BOTS_ORGS = [
    ("Freqtrade Org", "trading_bot", 2017, "UNKNOWN", "open_source"),
    ("Hummingbot Foundation", "open_source", 2019, "USA", "open_source"),
    ("CCXT Ecosystem", "open_source", 2017, "UNKNOWN", "open_source"),
    ("Ta-Lib Community", "open_source", None, "UNKNOWN", "open_source"),
    ("Backtesting.py Project", "open_source", 2019, "UNKNOWN", "open_source"),
    ("VectorBT Project", "open_source", 2020, "UNKNOWN", "open_source"),
    ("NautilusTrader", "open_source", 2021, "UNKNOWN", "open_source"),
    ("HftBacktest Project", "open_source", 2021, "UNKNOWN", "open_source"),
    ("Awesome Quant List Maintainers", "open_source", None, "UNKNOWN", "open_source"),
    ("QuantLib Project", "open_source", 2000, "UNKNOWN", "open_source"),
    ("Lean CLI / QuantConnect OSS", "open_source", 2012, "USA", "open_source"),
    ("Zipline-Reloaded Maintainers", "open_source", 2020, "UNKNOWN", "open_source"),
    ("PyBroker Project", "open_source", 2022, "UNKNOWN", "open_source"),
    ("FinRL Project", "ml_trading", 2020, "USA", "academic"),
    ("ElegantRL Project", "ml_trading", 2021, "USA", "academic"),
    ("TensorTrade Project", "ml_trading", 2019, "UNKNOWN", "open_source"),
    ("Gym-AnyTrading", "ml_trading", 2019, "UNKNOWN", "open_source"),
    ("Stable-Baselines3 Finance Experiments", "ml_trading", None, "UNKNOWN", "academic"),
    ("TradingGym Research Forks", "ml_trading", None, "UNKNOWN", "academic"),
    ("Qlib Microsoft Research", "ml_trading", 2020, "China", "academic"),
]

# Flatten helper lists that used invalid org_type — normalize relative_value/event_driven
def _all_raw_tuples():
    buckets = [
        FAMOUS_SEEDS,
        QUANT_SYSTEMATIC,
        PROP_HFT_MM,
        MULTI_STRAT_POD,
        CRYPTO_AND_DIGITAL,
        ASIA_EUROPE_SPECIALISTS,
        ALT_DATA_ML_ACADEMIC,
        INDEPENDENT_AND_DOCUMENTED_TRADERS,
        VOL_OPTIONS_EVENT,
        ADDITIONAL_PROP_AND_ALGO,
        OPEN_SOURCE_AND_BOTS_ORGS,
    ]
    out = []
    for b in buckets:
        out.extend(b)
    return out


ORG_TYPE_NORMALIZE = {
    "relative_value": "multi_strat",
    "event_driven": "multi_strat",
}


def iter_organization_seeds():
    seen = set()
    for name, org_type, founded, hq, tier in _all_raw_tuples():
        key = name.lower().strip()
        if key in seen:
            continue
        seen.add(key)
        yield {
            "name": name,
            "org_type": ORG_TYPE_NORMALIZE.get(org_type, org_type),
            "founded_year": founded,
            "headquarters": hq if hq else "UNKNOWN",
            "discovery_tier": tier,
        }
